version: 2
jobs:
  build:
    working_directory: ~/slab
    docker:
      - image: circleci/golang:1.8.1
      
    steps:
      - checkout
      - restore_cache:
          keys:
              - glide-cache-{{ checksum "glide.lock" }}
      - run:
          name: Install dependencies if not cached
          command: |
              if [ -d ./vendor ]; then
                  echo "vendor directory found"
              else
                  echo "vendor directory not found"
                  curl https://glide.sh/get | sh
                  glide install
              fi
      - save_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
          paths:
              - vendor
  test:
    working_directory: ~/slab
    docker:
      - image: circleci/golang:1.8.1
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
      - run: go test $(go list ./... | grep -v /vendor/)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build