version: 2
jobs:
  build:
    working_directory: ~/slab
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/slab
      
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v
      - save_cache:
          key: src-{{ .Branch }}-{{ .Revision }}
          paths:
            - "src/"
  test:
    working_directory: ~/slab
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/slab
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          key: src-{{ .Branch }}-{{ .Revision }}
      - run: go test -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build